server {
    server_name operacional.upsystem.cloud;

    location /api/ {
        proxy_pass http://127.0.0.1:3011/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location / {
        proxy_pass http://127.0.0.1:3010;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/operacional.upsystem.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/operacional.upsystem.cloud/privkey.pem;
}

server {
    listen 80;
    server_name operacional.upsystem.cloud;
    return 301 https://$host$request_uri;
}
